"""Data models for equities shadow trading."""
import json
from dataclasses import dataclass, field, asdict
from datetime import datetime, date
from typing import Optional
from enum import Enum


class SignalType(str, Enum):
    """Types of trading signals."""
    ENTRY_LONG = "ENTRY_LONG"
    EXIT_LONG = "EXIT_LONG"
    STOP_LOSS = "STOP_LOSS"
    HOLD = "HOLD"


class ExitReason(str, Enum):
    """Reasons for exiting a position."""
    SIGNAL = "signal"  # Strategy exit signal
    STOP_LOSS = "stop_loss"  # Hit stop loss
    TIMEOUT = "timeout"  # Max holding period exceeded
    KILL_SWITCH = "kill_switch"  # Risk management triggered
    MANUAL = "manual"  # Manual intervention


@dataclass
class Position:
    """
    Open position state for equities.

    Adapted from crypto but with equity-specific fields.
    """
    symbol: str  # Stock ticker (e.g., "AAPL")
    strategy_id: str
    entry_date: date  # Entry date (daily bars)
    entry_price: float  # Fill price after friction
    shares: float  # Number of shares (can be fractional)
    notional_value: float  # Entry value in USD
    side: str = "LONG"  # Only LONG for now
    stop_loss_price: Optional[float] = None
    stop_loss_pct: float = 0.05  # Default 5% stop

    # Fundamental context at entry
    insider_intensity: Optional[float] = None
    revenue_cagr: Optional[float] = None

    @property
    def entry_datetime(self) -> datetime:
        """Convert entry date to datetime."""
        return datetime.combine(self.entry_date, datetime.min.time())

    def days_held(self, current_date: date) -> int:
        """Calculate days since entry."""
        return (current_date - self.entry_date).days

    def unrealized_pnl(self, current_price: float) -> float:
        """Calculate unrealized P&L at current price."""
        if self.side == "LONG":
            return self.notional_value * (current_price / self.entry_price - 1)
        else:
            return self.notional_value * (1 - current_price / self.entry_price)

    def unrealized_pnl_pct(self, current_price: float) -> float:
        """Calculate unrealized P&L percentage."""
        if self.side == "LONG":
            return (current_price / self.entry_price - 1) * 100
        else:
            return (1 - current_price / self.entry_price) * 100

    def should_stop_out(self, current_price: float) -> bool:
        """Check if position should be stopped out."""
        if self.stop_loss_price is not None:
            if self.side == "LONG":
                return current_price <= self.stop_loss_price
            else:
                return current_price >= self.stop_loss_price
        # Fallback to percentage-based stop
        return self.unrealized_pnl_pct(current_price) <= -self.stop_loss_pct * 100


@dataclass
class TradeLog:
    """
    Full trade state vector for logging.

    Captures all context needed for audit and analysis.
    """
    timestamp: str  # ISO format timestamp
    trade_date: str  # Trading date YYYY-MM-DD
    strategy_id: str
    symbol: str
    signal: str  # ENTRY_LONG, EXIT_LONG, STOP_LOSS

    # Price information
    price_at_signal: float
    simulated_fill: float
    shares: float
    notional_value: float

    # Market context
    spy_trend: float
    vix_regime: float
    market_regime: str

    # Fundamental context (at entry)
    insider_intensity: Optional[float] = None
    revenue_cagr: Optional[float] = None
    earnings_quality: Optional[float] = None

    # P&L (for exits only)
    pnl: Optional[float] = None
    pnl_pct: Optional[float] = None
    days_held: Optional[int] = None
    exit_reason: Optional[str] = None

    # Strategy expression
    gene_expression: str = ""

    # Commission/friction breakdown
    commission: Optional[float] = None
    slippage_estimate: Optional[float] = None

    def to_json(self) -> str:
        """Convert to JSON string."""
        return json.dumps(asdict(self), indent=None)

    @classmethod
    def from_json(cls, json_str: str) -> "TradeLog":
        """Create from JSON string."""
        data = json.loads(json_str)
        return cls(**data)


@dataclass
class Signal:
    """
    Trading signal generated by strategy evaluation.
    """
    symbol: str
    signal_type: SignalType
    strategy_id: str
    price: float
    timestamp: datetime

    # Strategy context
    gene_expression: str = ""

    # Market context
    spy_trend: float = 0.0
    vix_regime: float = 0.0
    market_regime: str = "unknown"

    # Fundamental context
    insider_intensity: Optional[float] = None
    revenue_cagr: Optional[float] = None
    earnings_quality: Optional[float] = None

    # Position sizing suggestion
    suggested_shares: Optional[float] = None
    suggested_stop_loss: Optional[float] = None


@dataclass
class PortfolioSnapshot:
    """
    Point-in-time portfolio state for tracking.
    """
    timestamp: str  # ISO format
    trade_date: str  # YYYY-MM-DD

    # Equity metrics
    equity: float
    cash: float
    positions_value: float

    # Performance
    total_pnl: float
    total_pnl_pct: float
    daily_pnl: float
    daily_pnl_pct: float

    # Risk metrics
    open_positions: int
    exposure_pct: float
    max_drawdown_pct: float

    # Trading stats
    total_trades: int
    winning_trades: int
    losing_trades: int
    win_rate: float

    # Market context
    spy_trend: float
    vix_level: float
    market_regime: str

    def to_json(self) -> str:
        """Convert to JSON string."""
        return json.dumps(asdict(self), indent=None)


@dataclass
class DailySummary:
    """
    End-of-day summary for reporting.
    """
    date: str  # YYYY-MM-DD

    # Portfolio
    starting_equity: float
    ending_equity: float
    daily_pnl: float
    daily_pnl_pct: float

    # Trading activity
    entries: int
    exits: int
    stop_losses: int

    # Position summary
    open_positions: int
    exposure_pct: float

    # Top movers
    best_trade: Optional[dict] = None  # {symbol, pnl, pnl_pct}
    worst_trade: Optional[dict] = None  # {symbol, pnl, pnl_pct}

    # New positions
    new_entries: list = field(default_factory=list)  # [{symbol, price, size}]

    # Closed positions
    closed_positions: list = field(default_factory=list)  # [{symbol, pnl, pnl_pct, days_held}]

    # Market context
    spy_change_pct: float = 0.0
    vix_level: float = 0.0
    market_regime: str = "unknown"

    def to_json(self) -> str:
        """Convert to JSON string."""
        return json.dumps(asdict(self), indent=None)
