"""
Strategy generator - uses LLM to generate and mutate strategies.

Asset-agnostic with configurable primitives via registry.
"""
import json
import re
import random
import logging
import time
from dataclasses import dataclass
from typing import Optional

from shared.evolution.mutator.llm_client import LLMClient
from shared.evolution.mutator.prompts import (
    get_generation_prompt,
    get_mutation_prompt,
    STRATEGY_THEMES,
)

logger = logging.getLogger(__name__)

# Maximum retry attempts for LLM calls
MAX_RETRIES = 3
RETRY_BACKOFF = [1, 2, 4]  # Seconds between retries


@dataclass
class GeneratedStrategy:
    """
    Strategy generated by LLM.

    Minimal representation for Phase 2A.
    """
    name: str
    entry_long: str
    exit_long: str
    rationale: Optional[str] = None
    mutation_type: Optional[str] = None
    mutation_description: Optional[str] = None

    def to_dict(self) -> dict:
        """Convert to dict format expected by parser."""
        return {
            "strategy_name": self.name,
            "entry_long": self.entry_long,
            "exit_long": self.exit_long,
            "entry_short": None,
            "exit_short": None,
        }


class StrategyGenerator:
    """
    Generates trading strategies using LLM.

    Handles:
    - Initial strategy generation from themes
    - Mutation of existing strategies based on performance
    - Response parsing and validation
    - Retry logic for failures
    """

    # Allowed primitives for validation
    ALLOWED_PRIMITIVES = {
        "ema_trend",
        "price_position",
        "norm_rsi",
        "bb_position",
        "bb_width_percentile",
        "volume_intensity",
        "vwap_distance",
        "atr_regime",
        "atr_percentile",
    }

    def __init__(
        self,
        llm_client: LLMClient,
        market_filter_name: str = "btc_trend",
    ):
        """
        Initialize generator.

        Args:
            llm_client: LLM client instance
            market_filter_name: Name of market filter primitive (e.g., "btc_trend")
        """
        self.llm_client = llm_client
        self.market_filter_name = market_filter_name
        # Add market filter to allowed primitives
        self._allowed = self.ALLOWED_PRIMITIVES | {market_filter_name}

    def generate(self, theme: Optional[str] = None) -> Optional[GeneratedStrategy]:
        """
        Generate a new strategy from scratch.

        Args:
            theme: Optional strategy theme. If None, picks random theme.

        Returns:
            GeneratedStrategy or None if all retries fail
        """
        if theme is None:
            theme = random.choice(STRATEGY_THEMES)

        prompt = get_generation_prompt(
            theme=theme,
            market_filter_name=self.market_filter_name,
        )

        return self._call_with_retry(
            prompt=prompt,
            context={"action": "generate", "theme": theme},
        )

    def mutate(
        self,
        strategy: GeneratedStrategy,
        sharpe: float,
        win_rate: float,
        max_dd: float,
        trade_count: int,
    ) -> Optional[GeneratedStrategy]:
        """
        Mutate an existing strategy based on performance.

        Args:
            strategy: Strategy to mutate
            sharpe: Sharpe ratio from backtest
            win_rate: Win rate as decimal
            max_dd: Max drawdown as decimal
            trade_count: Number of trades

        Returns:
            Mutated GeneratedStrategy or None if all retries fail
        """
        prompt = get_mutation_prompt(
            strategy_name=strategy.name,
            entry_long=strategy.entry_long,
            exit_long=strategy.exit_long,
            sharpe=sharpe,
            win_rate=win_rate,
            max_dd=max_dd,
            trade_count=trade_count,
            market_filter_name=self.market_filter_name,
        )

        return self._call_with_retry(
            prompt=prompt,
            context={"action": "mutate", "parent": strategy.name},
        )

    def _call_with_retry(
        self,
        prompt: str,
        context: dict,
    ) -> Optional[GeneratedStrategy]:
        """
        Call LLM with retry logic.

        Args:
            prompt: Prompt to send
            context: Context for logging

        Returns:
            GeneratedStrategy or None if all retries fail
        """
        last_error = None

        for attempt in range(MAX_RETRIES):
            try:
                response = self.llm_client.generate(prompt, context)
                strategy = self._parse_response(response)

                if strategy:
                    # Validate the strategy
                    validation_error = self._validate_strategy(strategy)
                    if validation_error:
                        logger.warning(
                            f"Validation failed (attempt {attempt + 1}): {validation_error}"
                        )
                        last_error = validation_error
                        # Add error feedback to prompt for retry
                        prompt = self._add_error_feedback(prompt, validation_error)
                    else:
                        return strategy
                else:
                    last_error = "Failed to parse JSON response"
                    logger.warning(f"Parse failed (attempt {attempt + 1})")

            except Exception as e:
                last_error = str(e)
                logger.warning(f"LLM call failed (attempt {attempt + 1}): {e}")

            # Wait before retry (except on last attempt)
            if attempt < MAX_RETRIES - 1:
                time.sleep(RETRY_BACKOFF[attempt])

        logger.error(f"All {MAX_RETRIES} attempts failed. Last error: {last_error}")
        return None

    def _parse_response(self, response: str) -> Optional[GeneratedStrategy]:
        """
        Parse LLM response to extract strategy JSON.

        Args:
            response: Raw LLM response text

        Returns:
            GeneratedStrategy or None if parsing fails
        """
        # Try to extract JSON from response
        # LLM might include markdown code blocks
        json_match = re.search(r"```(?:json)?\s*(.*?)\s*```", response, re.DOTALL)
        if json_match:
            json_str = json_match.group(1)
        else:
            # Try to find raw JSON
            json_match = re.search(r"\{[^{}]*\}", response, re.DOTALL)
            if json_match:
                json_str = json_match.group(0)
            else:
                return None

        try:
            data = json.loads(json_str)
        except json.JSONDecodeError:
            return None

        # Extract required fields
        name = data.get("strategy_name", "")
        entry_long = data.get("entry_long", "")
        exit_long = data.get("exit_long", "")

        if not name or not entry_long or not exit_long:
            return None

        return GeneratedStrategy(
            name=name,
            entry_long=entry_long,
            exit_long=exit_long,
            rationale=data.get("rationale"),
            mutation_type=data.get("mutation_type"),
            mutation_description=data.get("mutation_description"),
        )

    def _validate_strategy(self, strategy: GeneratedStrategy) -> Optional[str]:
        """
        Validate strategy against constraints.

        Args:
            strategy: Strategy to validate

        Returns:
            Error message string or None if valid
        """
        # Check market filter is present in entry
        if self.market_filter_name not in strategy.entry_long:
            return f"Entry must include {self.market_filter_name}() check"

        # Check market filter has >= 0 condition
        filter_pattern = rf"{self.market_filter_name}\(\d+\)\s*>=\s*0"
        if not re.search(filter_pattern, strategy.entry_long):
            return f"Entry must include '{self.market_filter_name}(N) >= 0' check"

        # Extract all function calls
        func_pattern = re.compile(r"(\w+)\([^)]*\)")
        entry_funcs = set(func_pattern.findall(strategy.entry_long))
        exit_funcs = set(func_pattern.findall(strategy.exit_long))
        all_funcs = entry_funcs | exit_funcs

        # Check all primitives are allowed
        unknown = all_funcs - self._allowed
        if unknown:
            return f"Unknown primitives: {', '.join(unknown)}"

        # Check primitive count (max 5 per expression)
        if len(entry_funcs) > 5:
            return f"Entry has too many primitives: {len(entry_funcs)} > 5"
        if len(exit_funcs) > 5:
            return f"Exit has too many primitives: {len(exit_funcs)} > 5"

        # Check parameters are integers (basic check)
        param_pattern = re.compile(r"\(([^)]+)\)")
        for match in param_pattern.finditer(strategy.entry_long + " " + strategy.exit_long):
            params = match.group(1)
            for param in params.split(","):
                param = param.strip()
                if param:
                    try:
                        # Allow integers and simple floats like 2.0
                        float(param)
                    except ValueError:
                        return f"Invalid parameter: {param}"

        return None  # Valid

    def _add_error_feedback(self, prompt: str, error: str) -> str:
        """Add error feedback to prompt for retry."""
        feedback = f"\n\n## IMPORTANT: Previous attempt failed with error:\n{error}\n\nPlease fix this issue and try again."
        return prompt + feedback


def generate_initial_population(
    generator: StrategyGenerator,
    size: int = 5,
    custom_themes: list[str] | None = None,
) -> list[GeneratedStrategy]:
    """
    Generate initial population of strategies.

    Args:
        generator: StrategyGenerator instance
        size: Number of strategies to generate
        custom_themes: Optional list of themes to use instead of defaults

    Returns:
        List of generated strategies (may be smaller than size if failures)
    """
    strategies = []

    # Use custom themes if provided, otherwise use defaults
    theme_pool = custom_themes if custom_themes else STRATEGY_THEMES
    themes = random.sample(theme_pool, min(size, len(theme_pool)))
    if len(themes) < size:
        themes.extend(random.choices(theme_pool, k=size - len(themes)))

    for theme in themes:
        strategy = generator.generate(theme=theme)
        if strategy:
            strategies.append(strategy)
            logger.info(f"Generated: {strategy.name}")
        else:
            logger.warning(f"Failed to generate strategy for theme: {theme}")

    return strategies
